ss://YWVzLTI1Ni1nY206ODgwMTMzOWUtOGVkMy00Mzg5LTlkMWQtMmYyMTFjY2YwN2Jl@194.165.59.93:442#%F0%9F%86%94configfa%20%F0%9F%94%92%20SS-TCP-TLS%20%E2%9D%94%20XX%20113ms
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpjYzI3YTMwMTJkODFhNDRj@213.156.137.142:43660#%F0%9F%86%94configfa%20%F0%9F%94%92%20SS-TCP-TLS%20%E2%9D%94%20XX%20213ms
