ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpJT085aHR0WDFWUWdXVkJWcEVrbnpt@45.95.232.236:4248#%F0%9F%86%94freeconfigsplus%20%F0%9F%94%92%20SS-TCP-TLS%20%E2%9D%94%20XX%20161ms
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpZUUZtakthYW1TclBxVnkxanRYRVg0@212.192.14.226:41968#%F0%9F%86%94freeconfigsplus%20%F0%9F%94%92%20SS-TCP-TLS%20%E2%9D%94%20XX%20down
