ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpjdklJODVUclc2bjBPR3lmcEhWUzF1@45.87.175.183:8080#%40Filter_breaker-27
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpmOGY3YUN6Y1BLYnNGOHAz@195.181.160.6:990#%40Filter_breaker-58
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpjdklJODVUclc2bjBPR3lmcEhWUzF1@45.87.175.199:8080#%40Filter_breaker-4
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpReGJDMmFvdVdsbGwwV0ZIc1phTnpZ@77.83.246.74:443#%40Filter_breaker-2
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTp5WUxpRTBMT3NyMEN3SWpiaUNTTHky@147.45.235.63:49115#%40Filter_breaker-35
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpRQ1hEeHVEbFRUTUQ3anRnSFVqSW9q@45.87.175.170:8080#%40Filter_breaker-19
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTprMWRCT21PQjRvcWk3VW1wMzdhMWJR@82.38.31.214:8080#%40Filter_breaker-28
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpvWklvQTY5UTh5aGNRVjhrYTNQYTNB@193.29.139.144:8080#%40Filter_breaker-31
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTprMWRCT21PQjRvcWk3VW1wMzdhMWJR@82.38.31.199:8080#%40Filter_breaker-6
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTprMWRCT21PQjRvcWk3VW1wMzdhMWJR@45.87.175.192:8080#%40Filter_breaker-29
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTprMWRCT21PQjRvcWk3VW1wMzdhMWJR@82.38.31.190:8080#%40Filter_breaker-34
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpvWklvQTY5UTh5aGNRVjhrYTNQYTNB@193.29.139.184:8080#%40Filter_breaker-37
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpmOGY3YUN6Y1BLYnNGOHAz@188.214.36.155:990#%40Filter_breaker-26
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpIV05zS3k2MXFQeW9EdHJFWUV0WnVr@5.129.214.186:6403#%F0%9F%87%B3%F0%9F%87%B1%5Bopenproxylist.com%5D
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTplbUYxNW9TSWg3SU8ycVV0d3ZER2Rx@62.210.88.22:443#%F0%9F%87%AB%F0%9F%87%B7%20Paris%2C%20IDF%2C%20France
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpjdklJODVUclc2bjBPR3lmcEhWUzF1@45.87.175.192:8080#BESTIIVPNBOT
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTprMWRCT21PQjRvcWk3VW1wMzdhMWJR@82.38.31.208:8080#Emadt3ch%20%F0%9F%87%B3%F0%9F%87%B1%20%60
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTprMWRCT21PQjRvcWk3VW1wMzdhMWJR@82.38.31.179:8080#%F0%9F%87%B3%F0%9F%87%B1%20The%20Netherlands
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpvek5YSExmRzlXZTdTUlpoMWtlbmNq@77.83.246.74:443#%F0%9F%87%B5%F0%9F%87%B1%20Poland
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpPaUxSN2FBMGs1akp4djB1aWtRbFRV@78.129.140.11:443#%40v2FreeHub%20%F0%9F%87%AC%F0%9F%87%A7%60
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpPVGg2U1pXUkZKS0QxYUdKa2p3eml1@77.83.246.74:443#%40v2FreeHub%20%F0%9F%87%B5%F0%9F%87%B1
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNToyTmg1YVBUWU5OcHptNHRQTjhQc3ZG@194.87.45.189:443#%40v2FreeHub%20%F0%9F%87%AA%F0%9F%87%B8
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpMZTZkVldOM3FyNkZxV3BuWnB6N0Zz@89.185.84.185:443#%40v2FreeHub%20%F0%9F%87%AC%F0%9F%87%A7
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTprMWRCT21PQjRvcWk3VW1wMzdhMWJR@82.38.31.218:8080#%E2%99%A8%EF%B8%8F%20%40PlanB_net%20%D9%85%D9%86%D8%A8%D8%B9%20%DA%A9%D8%A7%D9%86%D9%81%DB%8C%DA%AF%20%D9%88%20%D9%BE%D8%B1%D9%88%DA%A9%D8%B3%DB%8C%20%D8%B1%D8%A7%DB%8C%DA%AF%D8%A7%D9%86
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTp6TVJoQkVQTldBRnNaRjQ1YmVjcWdp@fox-usa.outlinekeys.net:34868#BESTIIVPNBOT
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTp1RVdNMTV0Q3JROUJla29BVldRZzB6@81.19.141.45:443#%F0%9F%87%A9%F0%9F%87%AA%20Exclusive%20SH%CE%9EN%E2%84%A2%20miner
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpRQ1hEeHVEbFRUTUQ3anRnSFVqSW9q@45.87.175.165:8080#%F0%9F%87%B3%F0%9F%87%B1%20Exclusive%20SH%CE%9EN%E2%84%A2%20miner
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpCY3FBSDk4VFp2QW9jR01Za1F6eWMx@77.83.246.74:443#%F0%9F%87%B5%F0%9F%87%B1%20Exclusive%20SH%CE%9EN%E2%84%A2%20miner
