trojan://6pRjKQJ0CWyFtG.9@198.57.27.27:12990?allowInsecure=0&sni=diningtable.electricbanana.click#%40%F0%9D%91%BD2_%F0%9D%91%B4%F0%9D%91%B6%F0%9D%91%AB_%F0%9D%91%BA%F0%9D%91%AF%F0%9D%91%B6%F0%9D%91%B7%20-%20%F0%9F%87%A8%F0%9F%87%A6%20%E2%9A%A1%20%7C
trojan://5fbEkKmVOdAY+8_-@217.69.10.156:16288?allowInsecure=1&sni=sweetdream.sweetthunder.click#%40Filter_breaker-70
trojan://e9GP-sYzrxL2RBjl@64.176.18.21:18415?allowInsecure=1&sni=quietplace.lazymountain.click#%40Filter_breaker-65
trojan://.ie4rghJuMkcf0oF@38.96.254.102:18509?allowInsecure=1&sni=shoppingmall.electricbanana.click#%40Filter_breaker-62
trojan://BaeSzHdfJIR13l67@70.34.218.149:11930?allowInsecure=1&sni=softpillow.silentrocket.click#%40Filter_breaker-67
trojan://9Hf6Xm7juWw.BsqI@216.238.122.246:10849?allowInsecure=1&sni=hotcoffee.angrypiano.click#%40Filter_breaker-68
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpmOGY3YUN6Y1BLYnNGOHAz@195.181.160.6:990#%40Filter_breaker-58
trojan://WmFcbQ1O%3DhAJd-i2@158.247.206.18:15974?allowInsecure=1&sni=kszfviehlrb.zwodhfgqaps.click#%40Filter_breaker-77
trojan://z-H_x58nS%3DVUaw.o@216.238.94.42:19939?allowInsecure=1&sni=xuhyqrwofidgl.zwodhfgqaps.click#%40Filter_breaker-78
trojan://V8cbmRo4T2Qd+JwW@216.238.120.105:16555?allowInsecure=1&sni=qdsbwfvjal.zwodhfgqaps.click#%40Filter_breaker-79
trojan://S40Vr.vnDP2BsCKF@103.43.75.230:13536?allowInsecure=1&sni=smartphone.angrypiano.click#%40Filter_breaker-69
trojan://2euhAfXj-1RMSEgK@155.138.164.81:13590?allowInsecure=1&sni=bookstore.bluetigeraa.click#%40Filter_breaker-74
trojan://.%2BQAJot50sDi6mvb@5.188.108.13:11790?allowInsecure=1&sni=runningshoes.purpletornado.click#%40Filter_breaker-7
trojan://.%2BQAJot50sDi6mvb@5.188.108.13:11790?allowInsecure=0&sni=runningshoes.purpletornado.click#%40%F0%9D%91%BD2_%F0%9D%91%B4%F0%9D%91%B6%F0%9D%91%AB_%F0%9D%91%BA%F0%9D%91%AF%F0%9D%91%B6%F0%9D%91%B7%20-%20%F0%9F%87%B2%F0%9F%87%A8%20%E2%9A%A1%20%7C%60
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpid0xLem5uNWx4T0p4WlBMcml6OXl1@81.19.141.45:443#%40Filter_breaker-1
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTp0cC0waHA1QUpUYWtWeUNEajl4UllR@91.107.186.156:1080#%40Filter_breaker-18
trojan://.ie4rghJuMkcf0oF@38.96.254.102:18509?allowInsecure=0&sni=shoppingmall.electricbanana.click#%40%F0%9D%91%BD2_%F0%9D%91%B4%F0%9D%91%B6%F0%9D%91%AB_%F0%9D%91%BA%F0%9D%91%AF%F0%9D%91%B6%F0%9D%91%B7%20-%20%F0%9F%87%A8%F0%9F%87%A6%20%E2%9A%A1%20%7C
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpjdklJODVUclc2bjBPR3lmcEhWUzF1@45.87.175.199:8080#%40Filter_breaker-4
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTo4SHRDN3JqNk5mWm5jWFl2QWpEVjV0@213.176.16.77:7022#%40Filter_breaker-24
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpReGJDMmFvdVdsbGwwV0ZIc1phTnpZ@77.83.246.74:443#%40Filter_breaker-2
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpjdklJODVUclc2bjBPR3lmcEhWUzF1@45.87.175.183:8080#%40Filter_breaker-27
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTprMWRCT21PQjRvcWk3VW1wMzdhMWJR@82.38.31.199:8080#%40Filter_breaker-6
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpRQ1hEeHVEbFRUTUQ3anRnSFVqSW9q@45.87.175.170:8080#%40Filter_breaker-19
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTprMWRCT21PQjRvcWk3VW1wMzdhMWJR@82.38.31.214:8080#%40Filter_breaker-28
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpvWklvQTY5UTh5aGNRVjhrYTNQYTNB@193.29.139.144:8080#%40Filter_breaker-31
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTp5WUxpRTBMT3NyMEN3SWpiaUNTTHky@147.45.235.63:49115#%40Filter_breaker-35
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTprMWRCT21PQjRvcWk3VW1wMzdhMWJR@45.87.175.192:8080#%40Filter_breaker-29
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpmOGY3YUN6Y1BLYnNGOHAz@188.214.36.155:990#%40Filter_breaker-26
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTprMWRCT21PQjRvcWk3VW1wMzdhMWJR@82.38.31.202:8080#%40Filter_breaker-33
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTprMWRCT21PQjRvcWk3VW1wMzdhMWJR@82.38.31.190:8080#%40Filter_breaker-34
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpvWklvQTY5UTh5aGNRVjhrYTNQYTNB@193.29.139.184:8080#%40Filter_breaker-37
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpUZE5ZOWl0NVRDbU9OeVlZeFlNZkZh@h110vpnch.outlinekeys.net:4248#BESTIIVPNBOT
