proxies:
  - {name: "[SS] @Rayan_Config-45.87.175.155-@beepassvpn_bot", server: 45.87.175.155, port: 8080, type: ss, cipher: chacha20-ietf-poly1305, password: k1dBOmOB4oqi7Ump37a1bQ, udp: true, tfo: false}