trojan://humanity@172.64.152.23:443?allowInsecure=0&sni=www.calmlunch.com&ws=1&wspath=%2Fassignment#%F0%9F%87%BA%F0%9F%87%B8%20%F0%9F%86%94vless_config%20%F0%9F%94%92%20TR-WS-N%2FA%20%F0%9F%87%BA%F0%9F%87%B8%20US%202ms
